//data reducers
export const SET_CLIENTS = 'SET_CLIENTS';
export const SET_CLIENT = 'SET_CLIENT';
export const SET_REVIEW = 'SET_REVIEW';
export const COMPANY_CREATE_REVIEW = 'COMPANY_CREATE_REVIEW';
export const SET_SEARCH_CLIENTS = 'SET_SEARCH_CLIENTS';
export const SET_SEARCH_CLIENT = 'SET_SEARCH_CLIENT';
export const SET_AVAILABLE_TRIPS = 'SET_AVAILABLE_TRIPS';
export const SET_AVAILABLE_FUTURE_TRIPS = 'SET_AVAILABLE_FUTURE_TRIPS';
export const SET_AVAILABLE_TRIP = 'SET_AVAILABLE_TRIP';
export const SET_RE_AVAILABLE_TRIPS = 'SET_RE_AVAILABLE_TRIPS';
export const SET_TRIPS = 'SET_TRIPS';
export const SET_TRIP = 'SET_TRIP';
export const LOADING_DATA = 'LOADING_DATA';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_BOOKING_SUCCESS = 'ADD_BOOKING_SUCCESS';
export const CANCEL_BOOKING_SUCCESS = 'CANCEL_BOOKING_SUCCESS';
export const RE_BOOKING_SUCCESS = 'RE_BOOKING_SUCCESS';
export const UPDATE_TICKETSCOUNT_SUCCESS = 'UPDATE_TICKETSCOUNT_SUCCESS';
export const UPDATE_SEAT_SUCCESS = 'UPDATE_SEAT_SUCCESS';
export const UPDATE_SEAT_SUCCESS1 = 'UPDATE_SEAT_SUCCESS1';
export const ADD_CART_FAIL = 'ADD_CART_FAIL';
export const SET_CART = 'SET_CART';
export const DELETE_TRIP_CART = 'DELETE_TRIP_CART';
export const SET_BOOKINGS = 'SET_BOOKINGS';
export const SET_BOOKING = 'SET_BOOKING';
export const EDIT_STATUS = 'EDIT_STATUS';
export const EDIT_USER = 'EDIT_USER';

//UI reducers
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SERVER_ERROR = 'SERVER_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SET_ERROR = 'SET_ERROR';
export const SET_ERRORS_SIGNUP_COMPANY = 'SET_ERRORS_SIGNUP_COMPANY';
export const SET_ERROR_TRIP = 'SET_ERROR_TRIP';
export const SET_ERROR_VEHICLE = 'SET_ERROR_VEHICLE';
export const SET_ERROR_LOCATION = 'SET_ERROR_LOCATION';
export const SET_ERROR_EMPLOYEE = 'SET_ERROR_EMPLOYEE';
export const SET_ERROR_COMPANY = 'SET_ERROR_COMPANY';
export const SET_ERROR_USER_BOOKING = 'SET_ERROR_USER_BOOKING';
export const SET_ERROR_USER = 'SET_ERROR_USER';
export const SET_ERROR_PAYMENTACCOUNT = 'SET_ERROR_PAYMENTACCOUNT';

//user reducers
export const LOADING_USER = 'LOADING_USER';
export const SET_USER = 'SET_USER';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const ADD_TRIP = 'ADD_TRIP';
export const DELETE_TRIP = 'DELETE_TRIP';
export const EDIT_TRIP = 'EDIT_TRIP';

export const SET_VEHICLES = 'SET_VEHICLES';
export const SET_VEHICLE = 'SET_VEHICLE';
export const ADD_VEHICLE = 'ADD_VEHICLE';
export const DELETE_VEHICLE = 'DELETE_VEHICLE';
export const EDIT_VEHICLE = 'EDIT_VEHICLE';

export const SET_LOCATIONS = 'SET_LOCATIONS';
export const SET_LOCATION = 'SET_LOCATION';
export const ADD_LOCATION = 'ADD_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const EDIT_LOCATION = 'EDIT_LOCATION';

export const SET_REFUNDS = 'SET_REFUNDS';
export const SET_REFUND = 'SET_REFUND';
export const EDIT_REFUND = 'EDIT_REFUND';

export const SET_EMPLOYEES = 'SET_EMPLOYEES';
export const SET_EMPLOYEE = 'SET_EMPLOYEE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';

export const SET_USER_BOOKINGS = 'SET_USER_BOOKINGS';
export const SET_USER_BOOKING = 'SET_USER_BOOKING';
export const ADD_USER_BOOKING = 'ADD_USER_BOOKING';
export const DELETE_USER_BOOKING = 'DELETE_USER_BOOKING';
export const EDIT_USER_BOOKING = 'EDIT_USER_BOOKING';

// export const SET_COMPANIES = "SET_COMPANIES";
export const SET_COMPANY = 'SET_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const EDIT_COMPANY = 'EDIT_COMPANY';

export const SET_PAYMENTACCOUNTS = 'SET_PAYMENTACCOUNTS';
export const SET_PAYMENTACCOUNT = 'SET_PAYMENTACCOUNT';
