import {StyleSheet, Dimensions} from 'react-native';
import {linear} from 'react-native/Libraries/Animated/Easing';

const styles = StyleSheet.create({
  image: {
    width: Dimensions.get('screen').width,

    height: '99%',
    resizeMode: 'contain',
    alignItems: 'center',
    borderBottomLeftRadius: 60,
    // marginHorizontal: 10,
    justifyContent: 'center',
  },
  title3: {
    // marginTop: -10,
    fontSize: 45,
    fontWeight: 'bold',
    color: 'white',
    // borderWidth: 2,
    // textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowColor: '#87c830',
    textShadowOffset: {width: -6, height: 6},
    textShadowRadius: 10,
    // width: '70%',
    alignSelf: 'center',
    // alignItems: 'center',
    justifyContent: 'center',
    // marginLeft: 15,
    // marginBottom: -10,
    // fontVariant: 'gray',
  },
  title: {
    marginTop: 20,
    fontSize: 25,
    fontWeight: 'bold',
    color: 'white',
    alignSelf: 'center',
    textShadowColor: '#87c830',
    textShadowOffset: {width: -6, height: 6},
    textShadowRadius: 10,
    // width: '70%',
    // marginLeft: 15,
  },
  title2: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
    alignSelf: 'center',
    textShadowColor: '#87c830',
    textShadowOffset: {width: -6, height: 6},
    textShadowRadius: 10,
    // width: '70%',
    // marginLeft: 15,
  },
  button: {
    backgroundColor: '#87c830',
    width: 280,
    height: 50,
    // borderRadius: 25,
    borderTopRightRadius: 40,
    borderBottomLeftRadius: 40,
    marginTop: 10,
    // marginLeft: 15,
    justifyContent: 'center',
    alignItems: 'center',
    bottom: 30,
    // padding: 10,
  },
  buttonText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },

  searchButton: {
    backgroundColor: '#fff',
    borderColor: '#87c830',
    borderWidth: 2,
    height: 60,
    width: Dimensions.get('screen').width - 80,
    borderRadius: 30,
    marginHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',

    paddingHorizontal: 30,
    alignItems: 'center',
    position: 'absolute',
    top: 20,
    zIndex: 100,
  },
  searchButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 20,
  },
});

export default styles;
